# Copyright 2026 Matrix Origin
# Test-only build of the unchanged RELEASE.2023-11-01T01-57-10Z source.
FROM golang:1.21.3-alpine3.18 AS builder
RUN apk add --no-cache git ca-certificates
WORKDIR /src
RUN git init && \
    git remote add origin https://github.com/minio/minio.git && \
    git fetch --depth=1 origin 55e713db0a367f6cccee00af49f00c269e6ca619 && \
    git checkout --detach FETCH_HEAD && \
    test "$(git rev-parse HEAD)" = 55e713db0a367f6cccee00af49f00c269e6ca619
ENV CGO_ENABLED=0
RUN MINIO_RELEASE=RELEASE go build -p 4 -trimpath \
    -ldflags="$(MINIO_RELEASE=RELEASE go run buildscripts/gen-ldflags.go 2023-11-01T01:57:10Z)" \
    -o /minio .

FROM alpine:3.18.4
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /src/LICENSE /licenses/minio/LICENSE
COPY --from=builder /minio /usr/bin/minio
ENTRYPOINT ["/usr/bin/minio"]
